---
deployment:
  tasks:
    - export REPOPATH=/home/scstroyby/repositories/scstroyby/*
    - export SITEPATH=/home/scstroyby/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH